
POST http://localhost:3040/register
Content-Type: application/json

{
    "username" : "John",
    "email": "John@gmail.com",
    "password": "password"
}


###

POST http://localhost:3040/login
Content-Type: application/json

{
    "email": "John@gmail.com",
    "password": "password"
}